# Generated by Django 4.2.20 on 2025-08-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_address_id_alter_coupon_id_alter_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Animal Health'), ('SW', 'Farming Equipment'), ('OW', 'Animal Feeds & Equipments')], max_length=2),
        ),
    ]
